// ai_infer.h - AI inference function (auto-generated by Python)
// Model: Random Forest (simplified to single decision tree)
// Features: temp, humi, vib_x, vib_y, vib_z
// Training data: 2696 samples
// Accuracy: 99.8%
// Note: vibration detection is handled by variance analysis in ai_thread.c,
//       this model focuses on temperature/humidity anomaly detection.

#ifndef AI_INFER_H
#define AI_INFER_H

// Returns: 0=normal, 1=anomaly (temperature-based)
static inline int ai_predict(float temp, float humi,
               int vib_x, int vib_y, int vib_z)
{
    // Extracted from Random Forest: temperature is the key feature
    // for non-vibration anomalies
    if (temp > 35.05) {
        return 1;
    }
    if (humi > 65.0) {
        return 1;
    }
    return 0;
}

#endif
